import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>excel</h1>
        <ol>
          <li>
            <details>
              <summary>excelの概要</summary>
              エクセルとは?
              <br />
              表計算ソフトのこと
              <br />
            </details>
          </li>
          <li>
            <details>
              <summary>関数の概要</summary>
              関数とは?
              <br />
              エクセル内にある内部プログラム
              <br />
            </details>
          </li>
        </ol>

        <ol>
          <li>
            <details>
              <summary>excelの概要</summary>
              エクセルとは?
              <br />
              表計算ソフトのこと
              <br />
            </details>
          </li>
          <li>
            <details>
              <summary>関数の概要</summary>
              関数とは?
              <br />
              エクセル内にある内部プログラム
              <br />
            </details>
          </li>
        </ol>
      </main>
    </>
  );
}
